version: "3.8"

services:
#  reverse-proxy:
#    image: nginx:latest
#    restart: always
#    container_name: nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - db
#      - cache
#    volumes:
#      - ./packages/config/nginx.conf:/etc/nginx/nginx.conf
#    extra_hosts:
#      - "host.docker.internal:host-gateway"

  db:
    image: mysql:5.7.39
    container_name: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=cetus

  cache:
    image: redis:6
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  db_data: